export const COMPILE = 'COMPILE'
export const COMPILE_SUCCESS = 'COMPILE_SUCCESS'
export const COMPILE_FAIL = 'COMPILE_FAIL'

export const SAVE_CODE = 'SAVE_CODE'
export const SAVE_CODE_SUCCESS = 'SAVE_CODE_SUCCESS'
export const SAVE_CODE_FAIL = 'SAVE_CODE_FAIL'

export const SAVE_STATE = 'SAVE_STATE'
export const SAVE_STATE_SUCCESS = 'SAVE_STATE_SUCCESS'
export const SAVE_STATE_FAIL = 'SAVE_STATE_FAIL'

export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE'
export const UPDATE_INDENTATION = 'UPDATE_INDENTATION'
export const TOGGLE_AUTOCOMPLETE = 'TOGGLE_AUTOCOMPLETE'
export const TOGGLE_LIVE_AUTOCOMPLETE = 'TOGGLE_LIVE_AUTOCOMPLETE'
export const TOGGLE_VIM = 'TOGGLE_VIM'
export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS'
export const CHANGE_LANG = 'CHANGE_LANG'
export const SHOW_INFO = 'SHOW_INFO'
export const FINISHED_BEER = 'FINISHED_BEER'

export const REGISTER_TEAM = 'REGISTER_TEAM'
export const REGISTER_TEAM_SUCCESS = 'REGISTER_TEAM_SUCCESS'
export const REGISTER_TEAM_FAIL = 'REGISTER_TEAM_FAIL'

// Socket action types
export const SOCKET_CONNECT = 'SOCKET_CONNECT'
export const SOCKET_JOIN = 'SOCKET_JOIN'
export const SOCKET_COMPILE_ERROR = 'SOCKET_COMPILE_ERROR'
export const SOCKET_BEVERAGE_FINISH = 'SOCKET_BEVERAGE_FINISH'
